apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-pv
  namespace: blogging
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: sample
  claimRef:
    namespace: blogging
    name: gcs-pvc
  mountOptions:
    - implicit-dirs
    - uid=1001
    - gid=3003
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: CLOUD_STORAGE_BUCKET
    