apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-pvc
  namespace: blogging
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcs-pv
  storageClassName: sample